// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoneStock.Infrastructure.Persistence;

#nullable disable

namespace StoneStock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824194120_AddDeletePermissions")]
    partial class AddDeletePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoneStock.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.IncomingStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CustomsCost")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("OtherCost")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("PlateCountAdded")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("SaleCost")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("SaleCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("StoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StoneId");

                    b.ToTable("IncomingStocks");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "stones.view",
                            Key = "stones.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "stones.create",
                            Key = "stones.create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "stones.edit",
                            Key = "stones.edit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "incomingstock.view",
                            Key = "incomingstock.view"
                        },
                        new
                        {
                            Id = 5,
                            Description = "incomingstock.create",
                            Key = "incomingstock.create"
                        },
                        new
                        {
                            Id = 6,
                            Description = "plates.view",
                            Key = "plates.view"
                        },
                        new
                        {
                            Id = 7,
                            Description = "plates.create",
                            Key = "plates.create"
                        },
                        new
                        {
                            Id = 8,
                            Description = "plates.edit",
                            Key = "plates.edit"
                        },
                        new
                        {
                            Id = 9,
                            Description = "cost.unit.view",
                            Key = "cost.unit.view"
                        },
                        new
                        {
                            Id = 10,
                            Description = "cost.currency.view",
                            Key = "cost.currency.view"
                        },
                        new
                        {
                            Id = 11,
                            Description = "cost.sale.view",
                            Key = "cost.sale.view"
                        },
                        new
                        {
                            Id = 12,
                            Description = "users.manage",
                            Key = "users.manage"
                        },
                        new
                        {
                            Id = 13,
                            Description = "settings.manage",
                            Key = "settings.manage"
                        },
                        new
                        {
                            Id = 14,
                            Description = "theme.manage",
                            Key = "theme.manage"
                        },
                        new
                        {
                            Id = 15,
                            Description = "notifications.view",
                            Key = "notifications.view"
                        },
                        new
                        {
                            Id = 16,
                            Description = "auditlog.view",
                            Key = "auditlog.view"
                        },
                        new
                        {
                            Id = 17,
                            Description = "qrscanlog.view",
                            Key = "qrscanlog.view"
                        },
                        new
                        {
                            Id = 18,
                            Description = "incomingstock.edit",
                            Key = "incomingstock.edit"
                        },
                        new
                        {
                            Id = 19,
                            Description = "stones.delete",
                            Key = "stones.delete"
                        },
                        new
                        {
                            Id = 20,
                            Description = "incomingstock.delete",
                            Key = "incomingstock.delete"
                        },
                        new
                        {
                            Id = 21,
                            Description = "plates.delete",
                            Key = "plates.delete"
                        });
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("IncomingStockId")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("QrCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SaleAmount")
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SoldByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("IncomingStockId");

                    b.HasIndex("PlateNo")
                        .IsUnique();

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("SoldByUserId");

                    b.HasIndex("StoneId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.QrScanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PlateId")
                        .HasColumnType("integer");

                    b.Property<string>("RawScannedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScannedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlateId");

                    b.HasIndex("ScannedByUserId");

                    b.ToTable("QrScanLogs");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsSystemRole = true,
                            Name = "Kullanici"
                        },
                        new
                        {
                            Id = 3,
                            IsSystemRole = true,
                            Name = "Goruntuleyici"
                        });
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        });
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Stone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsBelowMinimumStock")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stones");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("NotifyLowStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyNewStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyPlateSold")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("text");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpSenderEmail")
                        .HasColumnType("text");

                    b.Property<string>("SmtpSenderName")
                        .HasColumnType("text");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.TextureOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TextureOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cilalı"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Honlu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patlatma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fırçalanmış"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eskitme"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Doğal"
                        });
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.WarehouseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WarehouseOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Depo A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Depo B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Depo C"
                        });
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.IncomingStock", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneStock.Domain.Entities.Stone", "Stone")
                        .WithMany("IncomingStocks")
                        .HasForeignKey("StoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Stone");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Plate", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.IncomingStock", "IncomingStock")
                        .WithMany("Plates")
                        .HasForeignKey("IncomingStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneStock.Domain.Entities.User", "SoldByUser")
                        .WithMany()
                        .HasForeignKey("SoldByUserId");

                    b.HasOne("StoneStock.Domain.Entities.Stone", "Stone")
                        .WithMany("Plates")
                        .HasForeignKey("StoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingStock");

                    b.Navigation("SoldByUser");

                    b.Navigation("Stone");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.QrScanLog", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.Plate", "Plate")
                        .WithMany("QrScanLogs")
                        .HasForeignKey("PlateId");

                    b.HasOne("StoneStock.Domain.Entities.User", "ScannedByUser")
                        .WithMany()
                        .HasForeignKey("ScannedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plate");

                    b.Navigation("ScannedByUser");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneStock.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.User", b =>
                {
                    b.HasOne("StoneStock.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.IncomingStock", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Plate", b =>
                {
                    b.Navigation("QrScanLogs");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StoneStock.Domain.Entities.Stone", b =>
                {
                    b.Navigation("IncomingStocks");

                    b.Navigation("Plates");
                });
#pragma warning restore 612, 618
        }
    }
}
