export const COUNTRIES = [
  'Afganistan',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Andorra',
  'Angola',
  'Antigua ve Barbuda',
  'Arjantin',
  'Arnavutluk',
  'Avustralya',
  'Avusturya',
  'Azerbaycan',
  'Bahamalar',
  'Bahreyn',
  'Bangladeş',
  'Barbados',
  'Belarus',
  'Belçika',
  'Belize',
  'Benin',
  'Bhutan',
  'Birleşik Arap Emirlikleri',
  'Bolivya',
  'Bosna Hersek',
  'Botsvana',
  'Brezilya',
  'Brunei',
  'Bulgaristan',
  'Burkina Faso',
  'Burundi',
  'Çad',
  'Çekya',
  'Cezayir',
  'Karadağ',
  'Çin',
  'Cibuti',
  'Danimarka',
  'Dominik Cumhuriyeti',
  'Dominika',
  'Doğu Timor',
  'Ekvador',
  'Ekvator Ginesi',
  'El Salvador',
  'Endonezya',
  'Eritre',
  'Ermenistan',
  'Estonya',
  'Esvatini',
  'Etiyopya',
  'Fas',
  'Fiji',
  'Filipinler',
  'Filistin',
  'Finlandiya',
  'Fransa',
  'Gabon',
  'Gambiya',
  'Gana',
  'Grenada',
  'Guatemala',
  'Gine',
  'Gine-Bissau',
  'Guyana',
  'Güney Afrika',
  'Güney Kore',
  'Güney Sudan',
  'Gürcistan',
  'Haiti',
  'Hindistan',
  'Hırvatistan',
  'Hollanda',
  'Honduras',
  'Irak',
  'İran',
  'İrlanda',
  'İspanya',
  'İsrail',
  'İsveç',
  'İsviçre',
  'İtalya',
  'İzlanda',
  'Jamaika',
  'Japonya',
  'Kamboçya',
  'Kamerun',
  'Kanada',
  'Karadağ',
  'Katar',
  'Kazakistan',
  'Kenya',
  'Kırgızistan',
  'Kiribati',
  'Kolombiya',
  'Komorlar',
  'Kongo Cumhuriyeti',
  'Kongo Demokratik Cumhuriyeti',
  'Kosova',
  'Kosta Rika',
  'Kuveyt',
  'Kuzey Kore',
  'Kuzey Makedonya',
  'Küba',
  'Laos',
  'Lesotho',
  'Letonya',
  'Liberya',
  'Libya',
  'Lihtenştayn',
  'Litvanya',
  'Lübnan',
  'Lüksemburg',
  'Macaristan',
  'Madagaskar',
  'Malavi',
  'Maldivler',
  'Malezya',
  'Mali',
  'Malta',
  'Fas',
  'Marshall Adaları',
  'Meksika',
  'Mikronezya',
  'Mısır',
  'Moğolistan',
  'Moldova',
  'Monako',
  'Mozambik',
  'Myanmar',
  'Namibya',
  'Nauru',
  'Nepal',
  'Nijer',
  'Nijerya',
  'Nikaragua',
  'Norveç',
  'Orta Afrika Cumhuriyeti',
  'Özbekistan',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua Yeni Gine',
  'Paraguay',
  'Peru',
  'Polonya',
  'Portekiz',
  'Romanya',
  'Ruanda',
  'Rusya',
  'Saint Kitts ve Nevis',
  'Saint Lucia',
  'Saint Vincent ve Grenadinler',
  'Samoa',
  'San Marino',
  'Sao Tome ve Principe',
  'Senegal',
  'Seyşeller',
  'Sırbistan',
  'Sierra Leone',
  'Singapur',
  'Slovakya',
  'Slovenya',
  'Solomon Adaları',
  'Somali',
  'Sri Lanka',
  'Sudan',
  'Surinam',
  'Suriye',
  'Suudi Arabistan',
  'Şili',
  'Tacikistan',
  'Tanzanya',
  'Tayland',
  'Tayvan',
  'Togo',
  'Tonga',
  'Trinidad ve Tobago',
  'Tunus',
  'Türkiye',
  'Türkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukrayna',
  'Umman',
  'Uruguay',
  'Ürdün',
  'Vanuatu',
  'Vatikan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yeni Zelanda',
  'Yunanistan',
  'Zambiya',
  'Zimbabve',
]
  .filter((name, index, arr) => arr.indexOf(name) === index)
  .sort((a, b) => a.localeCompare(b, 'tr'))
