namespace StoneStock.Application.Catalog;

public record IncomingStockDto(
    int Id,
    int StoneId,
    string StoneName,
    DateOnly ArrivalDate,
    string SupplyType,
    string Supplier,
    string BatchCode,
    decimal Quantity,
    decimal Thickness,
    string Texture,
    string Warehouse,
    string SaleCurrency,
    decimal? SaleCost,
    string? Description,
    string CreatedByUserName,
    int PlateCountAdded,
    decimal TotalArea,
    DateTimeOffset CreatedAt);

public sealed record IncomingStockAdminDto(
    int Id,
    int StoneId,
    string StoneName,
    DateOnly ArrivalDate,
    string SupplyType,
    string Supplier,
    string BatchCode,
    decimal Quantity,
    decimal Thickness,
    string Texture,
    string Warehouse,
    string SaleCurrency,
    decimal? SaleCost,
    string? Description,
    string CreatedByUserName,
    int PlateCountAdded,
    decimal TotalArea,
    DateTimeOffset CreatedAt,
    decimal UnitCost,
    string CostCurrency,
    decimal CustomsCost,
    decimal ShippingCost,
    decimal OtherCost,
    decimal TotalAdditionalCost)
    : IncomingStockDto(Id, StoneId, StoneName, ArrivalDate, SupplyType, Supplier, BatchCode, Quantity,
        Thickness, Texture, Warehouse, SaleCurrency, SaleCost, Description, CreatedByUserName, PlateCountAdded,
        TotalArea, CreatedAt);

public sealed record UpdateIncomingStockRequest(
    DateOnly ArrivalDate,
    string SupplyType,
    string Supplier,
    decimal Quantity,
    decimal Thickness,
    string Texture,
    string Warehouse,
    decimal UnitCost,
    string CostCurrency,
    string SaleCurrency,
    decimal? SaleCost,
    string? Description,
    decimal CustomsCost,
    decimal ShippingCost,
    decimal OtherCost);

public sealed record CreateIncomingStockRequest(
    int StoneId,
    DateOnly ArrivalDate,
    string SupplyType,
    string Supplier,
    decimal Quantity,
    decimal Thickness,
    string Texture,
    string Warehouse,
    decimal UnitCost,
    string CostCurrency,
    string SaleCurrency,
    decimal? SaleCost,
    string? Description,
    decimal CustomsCost,
    decimal ShippingCost,
    decimal OtherCost);
